package org.danforthcenter.genome.rootarch.rsagia.app2;

import org.danforthcenter.genome.rootarch.rsagia.dbfunctions.MetadataDBFunctions;
import org.danforthcenter.genome.rootarch.rsagia2.UserAccess;
import org.jooq.Record;
import org.jooq.Result;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddExperimentFrame extends JDialog implements ActionListener {
    private JComboBox organismComboBox;
    private JTextField codeField;
    private JTextField descField;
    private JButton addButton;
    private JPanel panel1;
    private MetadataDBFunctions mdf;
    private String user;


    public AddExperimentFrame() {
        super(null, "Add Experiment", ModalityType.APPLICATION_MODAL);
        $$$setupUI$$$();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.getContentPane().add(this.panel1);
        pack();

        addButton.addActionListener(this);
        this.mdf = new MetadataDBFunctions();

        loadOrganisms();
    }

    private void loadOrganisms() {
        DefaultComboBoxModel organisms = new DefaultComboBoxModel();
        Result<Record> organismRecord = this.mdf.selectAllOrganism();
        for (Record r : organismRecord) {
            organisms.addElement((String) r.getValue("organism_name"));
        }
        organismComboBox.setModel(organisms);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == addButton) {
            String organism = (String) organismComboBox.getSelectedItem();
            String newExperimentCode = codeField.getText();
            String description = descField.getText();
            Result<Record> experimentRecord = mdf.findExperimentFromOrganism(organism);
            String user = UserAccess.getCurrentUser();
            boolean check = true;
            for (Record r : experimentRecord) {
                if (newExperimentCode.equals((String) r.getValue("experiment_code"))) {
                    check = false;
                    JOptionPane.showMessageDialog(null, "This experiment is already added for organism " + organism, "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            if (check == true && !(newExperimentCode.length() == 3 && newExperimentCode.toUpperCase().equals(newExperimentCode) && mdf.isAlpha(newExperimentCode) == true)) {
                check = false;
                JOptionPane.showMessageDialog(null, "This experiment is not in valid format. The valid format is upper case 3 letter code.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            if (check == true) {
                mdf.insertExperiment(organism, newExperimentCode, description, user);
                JOptionPane.showMessageDialog(null, newExperimentCode + " is added for organism " + organism + " successfully.", null, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(280, 165));
        final JLabel label1 = new JLabel();
        label1.setText("Choose organism:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer2, gbc);
        organismComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(organismComboBox, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Experiment Code:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label2, gbc);
        codeField = new JTextField();
        codeField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(codeField, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer3, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Description:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label3, gbc);
        descField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(descField, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer4, gbc);
        addButton = new JButton();
        addButton.setText("Add");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(addButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
