/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CropWaitFrame.java
 *
 * Created on Jul 20, 2010, 1:19:34 PM
 */

package org.danforthcenter.genome.rootarch.rsagia.app2;

/**
 *
 * @author bm93
 */
public class CropWaitFrame extends javax.swing.JFrame {

	/** Creates new form CropWaitFrame */
	public CropWaitFrame() {
		initComponents();
	}

	public void setLabel(int cur, int max) {
		waitLabel.setText("Please waiting: saving " + cur + " of " + max
				+ " cropped image sets.");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		waitLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

		waitLabel.setText("Please wait: saving cropped images.");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap()
						.addComponent(waitLabel)
						.addContainerGap(157, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap()
						.addComponent(waitLabel)
						.addContainerGap(64, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CropWaitFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel waitLabel;
	// End of variables declaration//GEN-END:variables

}
