/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ErrorFrame.java
 *
 * Created on Aug 9, 2010, 12:30:48 PM
 */

package org.danforthcenter.genome.rootarch.rsagia.app2;

import java.io.PrintWriter;
import java.io.StringWriter;

/**
 *
 * @author bm93
 */
public class ErrorFrame extends javax.swing.JFrame {

	/** Creates new form ErrorFrame */
	public ErrorFrame(Throwable th) {
		initComponents();

		String msg = (th.getMessage() == null) ? "" : th.getMessage();
		StringWriter sw = new StringWriter();
		PrintWriter pw = new PrintWriter(sw, true);
		th.printStackTrace(pw);
		pw.flush();
		sw.flush();
		String eol = System.getProperty("line.separator");
		msg += eol + eol + sw.toString();

		this.textTextArea.append(msg);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		textTextArea = new javax.swing.JTextArea();

		setTitle("Error Message");

		textTextArea.setColumns(20);
		textTextArea.setEditable(false);
		textTextArea.setLineWrap(true);
		textTextArea.setRows(5);
		textTextArea
				.setText("An error has occured.  Please send the following text to the developer\nmaintaining this application.  It is recommended that you restart this\napplication:\n\n");
		jScrollPane1.setViewportView(textTextArea);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 454,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 405,
								Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ErrorFrame(new Exception("OH MY")).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea textTextArea;
	// End of variables declaration//GEN-END:variables

}
