/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManipPipelineFrame.java
 *
 * Created on May 10, 2010, 1:58:09 PM
 */

package org.danforthcenter.genome.rootarch.rsagia.app2;

import java.awt.Dimension;
import java.awt.event.ActionEvent;

import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author bm93
 */
public class ImageManipulationFrame extends javax.swing.JFrame implements
		java.awt.event.ActionListener {

	protected ManipImagePanel mip;
	protected ImageToolsPanel itp;
	protected JPanel appPanel;

	/** Creates new form ManipPipelineFrame */
	public ImageManipulationFrame() {
		initComponents();

		this.setSize(new Dimension(900, 680));
		this.setPreferredSize(new Dimension(900, 680));
		BoxLayout bl = new BoxLayout(this.getContentPane(), BoxLayout.Y_AXIS);
		this.setLayout(bl);
		JPanel p = new JPanel();
		p.setPreferredSize(new Dimension(900, 540));
		p.setMinimumSize(new Dimension(900, 540));
		BoxLayout bl2 = new BoxLayout(p, BoxLayout.X_AXIS);
		p.setLayout(bl2);
		mip = new ManipImagePanel();
		mip.setMinimumSize(new Dimension(810, 580));
		mip.setSize(new Dimension(810, 580));
		mip.setPreferredScrollableViewportSize(new Dimension(800, 600));
		p.add(new JScrollPane(mip));
		itp = new ImageToolsPanel();
		itp.setSize(200, 610);
		itp.setMaximumSize(new Dimension(200, 1024));
		p.add(itp);
		itp.getZoomComboBox().addActionListener(this);
		this.add(p);
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		if (e.getSource() == itp.getZoomComboBox()) {
			mip.setScale(itp.getZoom(), itp.getZoom());
		}
	}

	public void setAppPanel(JPanel appPanel) {
		if (this.appPanel != null) {
			this.remove(appPanel);
		}

		this.appPanel = appPanel;
		this.add(appPanel);
		appPanel.setVisible(true);
		pack();
	}

	public ImageToolsPanel getItp() {
		return itp;
	}

	public ManipImagePanel getMip() {
		return mip;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		// TW 2014july21
		// setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ImageManipulationFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables

}
