/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RisPreprocessFrame.java
 *
 * Created on Jul 22, 2010, 1:06:45 PM
 */

package org.danforthcenter.genome.rootarch.rsagia.app2;

/**
 *
 * @author bm93
 */
public class RisPreprocessFrame extends javax.swing.JFrame {

	/** Creates new form RisPreprocessFrame */
	public RisPreprocessFrame() {
		initComponents();
	}

	public void setCount(int i, int total) {
		infoLabel.setText("Please wait.  Preprocessing " + i + " of " + total
				+ " images sets.");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		infoLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

		infoLabel.setText("Please wait.  Preprocessing 0 of 100 image sets.");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap()
						.addComponent(infoLabel)
						.addContainerGap(80, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap()
						.addComponent(infoLabel)
						.addContainerGap(70, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RisPreprocessFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel infoLabel;
	// End of variables declaration//GEN-END:variables

}
