//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.27 at 04:16:31 PM EST 
//

package org.danforthcenter.genome.rootarch.rsagia.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ImageTableFilter complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ImageTableFilter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateFilter" type="{}DateFilter"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageTableFilter", propOrder = { "dateFilter" })
public class ImageTableFilter {

	@XmlElement(name = "DateFilter", required = true)
	protected DateFilter dateFilter;

	/**
	 * Gets the value of the dateFilter property.
	 * 
	 * @return possible object is {@link DateFilter }
	 * 
	 */
	public DateFilter getDateFilter() {
		return dateFilter;
	}

	/**
	 * Sets the value of the dateFilter property.
	 * 
	 * @param value
	 *            allowed object is {@link DateFilter }
	 * 
	 */
	public void setDateFilter(DateFilter value) {
		this.dateFilter = value;
	}

}
