//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.27 at 04:16:31 PM EST 
//

package org.danforthcenter.genome.rootarch.rsagia.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the edu.duke.genome.rootarch.rsagia.xml
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _ImageTableFilter_QNAME = new QName("",
			"ImageTableFilter");
	private final static QName _Params_QNAME = new QName("", "params");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: edu.duke.genome.rootarch.rsagia.xml
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link DateFilter }
	 * 
	 */
	public DateFilter createDateFilter() {
		return new DateFilter();
	}

	/**
	 * Create an instance of {@link ImageTableFilter }
	 * 
	 */
	public ImageTableFilter createImageTableFilter() {
		return new ImageTableFilter();
	}

	/**
	 * Create an instance of {@link RootworkConfigType }
	 * 
	 */
	public RootworkConfigType createRootworkConfigType() {
		return new RootworkConfigType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link ImageTableFilter }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ImageTableFilter")
	public JAXBElement<ImageTableFilter> createImageTableFilter(
			ImageTableFilter value) {
		return new JAXBElement<ImageTableFilter>(_ImageTableFilter_QNAME,
				ImageTableFilter.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link RootworkConfigType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "params")
	public JAXBElement<RootworkConfigType> createParams(RootworkConfigType value) {
		return new JAXBElement<RootworkConfigType>(_Params_QNAME,
				RootworkConfigType.class, null, value);
	}

}
