/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.danforthcenter.genome.rootarch.rsagia2;

import java.io.File;

/**
 * Interface for applications to specify their working directories, what inputs
 * are required, etc. Useful for constructing a workflow based upon the final
 * output.
 * 
 * @author bm93
 */
public interface IApplication {
	/**
	 * The application's name is used for output, as well as determines the name
	 * of its subdirectory within the saved and sandbox directories.
	 * 
	 * @return The name of the application.
	 */
	public String getName();

	/**
	 * Returns the list of outputs that will be generated by this instance of
	 * the application.
	 * 
	 * @return The list of outputs of this instance.
	 */
	public int getOutputs();

	public OutputInfo getOutputInfo(File f, RsaImageSet ris);

	/**
	 * Returns the list of all possible outputs (depending on configuration) of
	 * this application class (could be static).
	 * 
	 * @return The list of outputs of this class.
	 */
	public int getPossibleOutputs();

	/**
	 * Returns optional inputs to this algorithm (for instance, a pre-cropped
	 * image to gia roots).
	 * 
	 * @return The list of optional inputs.
	 */
	public int getOptionalInputs();

	/**
	 * Returns the list of required inputs to this algorithm.
	 * 
	 * @return The list of required inputs.
	 */
	public int getRequiredInputs();

	/**
	 * Returns a string of identifier + information for display of an output
	 * info from this application.
	 * 
	 * @param oi
	 * @return
	 */
	public String getReviewString(OutputInfo oi);

	public boolean hasRequiredInput(RsaImageSet ris, ApplicationManager am);
}
