package org.danforthcenter.genome.rootarch.rsagia.app2;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import org.danforthcenter.genome.rootarch.rsagia.dbfunctions.OutputInfoDBFunctions;

public class AddGia2DConfigFrame extends JFrame implements ActionListener {
    private JTextArea area;
    private JButton addButton;
    private JPanel panel1;
    private JTextField nameText;
    private JLabel nameLabel;
    private JButton cancelButton;
    private JScrollPane scroll;
    private OutputInfoDBFunctions oidbf;

    public AddGia2DConfigFrame() {
        $$$setupUI$$$();
        this.setTitle("Add Gia2D Config");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.addButton.addActionListener(this);
        this.cancelButton.addActionListener(this);
        this.getContentPane().add(this.panel1);
        pack();

        this.oidbf = new OutputInfoDBFunctions();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == this.addButton) {
            String name = this.nameText.getText();
            String contents = this.area.getText();
            if (name.length() == 0) {
                JOptionPane.showMessageDialog(null, "Please enter the name.", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (contents.length() == 0) {
                JOptionPane.showMessageDialog(null, "Please enter the contents.", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (this.oidbf.checkSavedConfigNameExists(name, "giaroot_2d")) {
                JOptionPane.showMessageDialog(null, "Name already exists.", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    this.oidbf.insertSavedConfig(contents, name, "giaroot_2d");
                    JOptionPane.showMessageDialog(null, "The configuration is added successfully.", null, JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } catch (Exception e1) {
                    e1.printStackTrace();
                    JOptionPane.showMessageDialog(null, "The configuration is NOT added successfully.", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else if (e.getSource() == this.cancelButton) {
            this.dispose();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(800, 800));
        addButton = new JButton();
        addButton.setText("Add");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(addButton, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.insets = new Insets(10, 10, 10, 10);
        panel1.add(cancelButton, gbc);
        scroll = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 10);
        panel1.add(scroll, gbc);
        area = new JTextArea();
        scroll.setViewportView(area);
        nameLabel = new JLabel();
        nameLabel.setText("Name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 10, 10, 10);
        panel1.add(nameLabel, gbc);
        nameText = new JTextField();
        nameText.setMinimumSize(new Dimension(200, 24));
        nameText.setPreferredSize(new Dimension(200, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(nameText, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
