package org.danforthcenter.genome.rootarch.rsagia.app2;

import org.danforthcenter.genome.rootarch.rsagia.dbfunctions.MetadataDBFunctions;
import org.jooq.Record;
import org.jooq.Result;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

@SuppressWarnings("unchecked")
public class AddGenotypeFrame extends JDialog implements ActionListener {
    private MetadataDBFunctions mdf;
    private JComboBox<String> organismComboBox;
    private JTextField genotypeField;
    private JButton addButton;
    private JPanel panel1;

    public AddGenotypeFrame() {
        super(null, "Add Genotype", ModalityType.APPLICATION_MODAL);
        $$$setupUI$$$();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.getContentPane().add(this.panel1);
        this.addButton.addActionListener(this);
        this.mdf = new MetadataDBFunctions();
        loadOrganisms();
    }

    private void loadOrganisms() {
        DefaultComboBoxModel<String> organisms = new DefaultComboBoxModel<>();
        Result<Record> organismRecord = this.mdf.selectAllOrganism();
        for (Record r : organismRecord) {
            organisms.addElement((String) r.getValue("organism_name"));
        }
        this.organismComboBox.setModel(organisms);
        pack();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == this.addButton) {
            String organism = (String) this.organismComboBox.getSelectedItem();
            String genotype = this.genotypeField.getText();
            boolean check = true;
            if (organism == null) {
                JOptionPane.showMessageDialog(null, "Organism value cannot be empty.", "ERROR", JOptionPane.ERROR_MESSAGE);
                check = false;
            }
            if (check == true && genotype.isEmpty()) {
                check = false;
                JOptionPane.showMessageDialog(null, "You entered empty genotype value.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            if (check == true && this.mdf.checkGenotypeExists(organism, genotype)) {
                check = false;
                JOptionPane.showMessageDialog(null, "This genotype is already added.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            if (check == true) {
                try {
                    this.mdf.insertGenotype(organism, genotype);
                    JOptionPane.showMessageDialog(null, "The genotype is added successfully.", "INFO", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } catch (Exception e1) {
                    e1.printStackTrace();
                    JOptionPane.showMessageDialog(null, "The genotype is NOT added successfully.", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(250, 200));
        final JLabel label1 = new JLabel();
        label1.setText("Organism:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 10, 10);
        panel1.add(label1, gbc);
        organismComboBox = new JComboBox();
        organismComboBox.setLightWeightPopupEnabled(false);
        organismComboBox.setPreferredSize(new Dimension(120, 25));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(organismComboBox, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Genotype:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 0, 10, 0);
        panel1.add(label2, gbc);
        genotypeField = new JTextField();
        genotypeField.setPreferredSize(new Dimension(120, 25));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(genotypeField, gbc);
        addButton = new JButton();
        addButton.setText("Add");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 0, 10, 0);
        panel1.add(addButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
