package org.danforthcenter.genome.rootarch.rsagia.app2;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import org.danforthcenter.genome.rootarch.rsagia.dbfunctions.OutputInfoDBFunctions;

public class EditGia2DConfigFrame extends JFrame implements ActionListener {
    private JTextArea area;
    private JPanel panel1;
    private JScrollPane scroll;
    private JButton saveButton;
    private JButton cancelButton;
    private JTextField nameText;
    private JLabel nameLabel;
    private String selectedConfigName;
    private String configContents;
    private OutputInfoDBFunctions oidbf;

    public EditGia2DConfigFrame(String selectedConfigName) {
        $$$setupUI$$$();
        this.setTitle("Edit Gia2D Config");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.saveButton.addActionListener(this);
        this.cancelButton.addActionListener(this);
        this.getContentPane().add(this.panel1);
        pack();

        this.selectedConfigName = selectedConfigName;
        this.oidbf = new OutputInfoDBFunctions();
        this.configContents = this.oidbf.findSavedConfigContents(selectedConfigName, "giaroot_2d");
        this.nameText.setText(selectedConfigName);
        this.area.setText(this.configContents);
        this.area.setCaretPosition(0);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == this.saveButton) {
            String newName = this.nameText.getText();
            String newContents = this.area.getText();
            if (newName.length() == 0) {
                JOptionPane.showMessageDialog(null, "Config name is empty.", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (newContents.length() == 0) {
                JOptionPane.showMessageDialog(null, "Config contents are empty.", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (!newName.equals(this.selectedConfigName) && this.oidbf.checkSavedConfigNameExists(newName, "giaroot_2d")) {
                JOptionPane.showMessageDialog(null, "Name already exists.", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    if (!newContents.equals(this.configContents)) {
                        this.oidbf.moveSavedConfigToUnsavedConfig(this.selectedConfigName, "giaroot_2d");
                    }
                    this.oidbf.updateSavedConfig(newContents, newName, this.selectedConfigName, "giaroot_2d");
                    firePropertyChange("getall", null, null);
                    JOptionPane.showMessageDialog(null, "The configuration is edited successfully.", null, JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } catch (Exception e1) {
                    e1.printStackTrace();
                    JOptionPane.showMessageDialog(null, "The configuration is NOT edited successfully.", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else if (e.getSource() == this.cancelButton) {
            this.dispose();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(800, 800));
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.insets = new Insets(10, 10, 10, 10);
        panel1.add(cancelButton, gbc);
        nameLabel = new JLabel();
        nameLabel.setText("Name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 10, 10, 10);
        panel1.add(nameLabel, gbc);
        saveButton = new JButton();
        saveButton.setText("Save");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(saveButton, gbc);
        nameText = new JTextField();
        nameText.setMinimumSize(new Dimension(200, 24));
        nameText.setPreferredSize(new Dimension(200, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(nameText, gbc);
        scroll = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 10);
        panel1.add(scroll, gbc);
        area = new JTextArea();
        scroll.setViewportView(area);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
