package org.danforthcenter.genome.rootarch.rsagia.app2;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import org.danforthcenter.genome.rootarch.rsagia.dbfunctions.OutputInfoDBFunctions;

public class ViewGia2DConfigFrame extends JFrame implements ActionListener {
    private JTextArea area;
    private JPanel panel1;
    private JScrollPane scroll;
    private JButton okButton;
    private JTextField nameText;
    private JLabel nameLabel;
    private String selectedConfigName;
    private String configContents;
    private OutputInfoDBFunctions oidbf;

    public ViewGia2DConfigFrame(String selectedConfigName) {
        $$$setupUI$$$();
        this.setTitle("View Gia2D Config");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.okButton.addActionListener(this);
        this.getContentPane().add(this.panel1);
        pack();

        this.selectedConfigName = selectedConfigName;
        this.oidbf = new OutputInfoDBFunctions();
        this.configContents = this.oidbf.findSavedConfigContents(selectedConfigName, "giaroot_2d");
        this.nameText.setText(selectedConfigName);
        this.area.setText(this.configContents);
        this.area.setCaretPosition(0);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == this.okButton) {
            this.dispose();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(800, 800));
        nameLabel = new JLabel();
        nameLabel.setText("Name:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 10, 10, 10);
        panel1.add(nameLabel, gbc);
        nameText = new JTextField();
        nameText.setEditable(false);
        nameText.setMinimumSize(new Dimension(200, 24));
        nameText.setPreferredSize(new Dimension(200, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(nameText, gbc);
        okButton = new JButton();
        okButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        panel1.add(okButton, gbc);
        scroll = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 10);
        panel1.add(scroll, gbc);
        area = new JTextArea();
        area.setEditable(false);
        scroll.setViewportView(area);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
