/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.DatasetImageType;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetImageTypeRecord extends UpdatableRecordImpl<DatasetImageTypeRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -461949108;

    /**
     * Setter for <code>rsa_gia.dataset_image_type.dataset_id</code>.
     */
    public void setDatasetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.dataset_image_type.dataset_id</code>.
     */
    public Integer getDatasetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rsa_gia.dataset_image_type.image_type</code>.
     */
    public void setImageType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.dataset_image_type.image_type</code>.
     */
    public String getImageType() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DatasetImageType.DATASET_IMAGE_TYPE.DATASET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DatasetImageType.DATASET_IMAGE_TYPE.IMAGE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getImageType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getImageType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DatasetImageTypeRecord value1(Integer value) {
        setDatasetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DatasetImageTypeRecord value2(String value) {
        setImageType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DatasetImageTypeRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetImageTypeRecord
     */
    public DatasetImageTypeRecord() {
        super(DatasetImageType.DATASET_IMAGE_TYPE);
    }

    /**
     * Create a detached, initialised DatasetImageTypeRecord
     */
    public DatasetImageTypeRecord(Integer datasetId, String imageType) {
        super(DatasetImageType.DATASET_IMAGE_TYPE);

        set(0, datasetId);
        set(1, imageType);
    }
}
