/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.Dataset;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetRecord extends UpdatableRecordImpl<DatasetRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1154477894;

    /**
     * Setter for <code>rsa_gia.dataset.dataset_id</code>.
     */
    public void setDatasetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.dataset.dataset_id</code>.
     */
    public Integer getDatasetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rsa_gia.dataset.seed_id</code>.
     */
    public void setSeedId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.dataset.seed_id</code>.
     */
    public Integer getSeedId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rsa_gia.dataset.timepoint_d_t_value</code>.
     */
    public void setTimepointDTValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rsa_gia.dataset.timepoint_d_t_value</code>.
     */
    public String getTimepointDTValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Dataset.DATASET.DATASET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Dataset.DATASET.SEED_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Dataset.DATASET.TIMEPOINT_D_T_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSeedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTimepointDTValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSeedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTimepointDTValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DatasetRecord value1(Integer value) {
        setDatasetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DatasetRecord value2(Integer value) {
        setSeedId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DatasetRecord value3(String value) {
        setTimepointDTValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DatasetRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetRecord
     */
    public DatasetRecord() {
        super(Dataset.DATASET);
    }

    /**
     * Create a detached, initialised DatasetRecord
     */
    public DatasetRecord(Integer datasetId, Integer seedId, String timepointDTValue) {
        super(Dataset.DATASET);

        set(0, datasetId);
        set(1, seedId);
        set(2, timepointDTValue);
    }
}
