/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.Experiment;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentRecord extends UpdatableRecordImpl<ExperimentRecord> implements Record5<Integer, String, String, Integer, String> {

    private static final long serialVersionUID = -1085391130;

    /**
     * Setter for <code>rsa_gia.experiment.experiment_id</code>.
     */
    public void setExperimentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.experiment.experiment_id</code>.
     */
    public Integer getExperimentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rsa_gia.experiment.experiment_code</code>.
     */
    public void setExperimentCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.experiment.experiment_code</code>.
     */
    public String getExperimentCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rsa_gia.experiment.organism_name</code>.
     */
    public void setOrganismName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rsa_gia.experiment.organism_name</code>.
     */
    public String getOrganismName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rsa_gia.experiment.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>rsa_gia.experiment.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>rsa_gia.experiment.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rsa_gia.experiment.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Experiment.EXPERIMENT.EXPERIMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Experiment.EXPERIMENT.EXPERIMENT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Experiment.EXPERIMENT.ORGANISM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Experiment.EXPERIMENT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Experiment.EXPERIMENT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getExperimentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getExperimentCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrganismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getExperimentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExperimentCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrganismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value1(Integer value) {
        setExperimentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value2(String value) {
        setExperimentCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value3(String value) {
        setOrganismName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value4(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord values(Integer value1, String value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperimentRecord
     */
    public ExperimentRecord() {
        super(Experiment.EXPERIMENT);
    }

    /**
     * Create a detached, initialised ExperimentRecord
     */
    public ExperimentRecord(Integer experimentId, String experimentCode, String organismName, Integer userId, String description) {
        super(Experiment.EXPERIMENT);

        set(0, experimentId);
        set(1, experimentCode);
        set(2, organismName);
        set(3, userId);
        set(4, description);
    }
}
