/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.Genotype;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenotypeRecord extends UpdatableRecordImpl<GenotypeRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 114437832;

    /**
     * Setter for <code>rsa_gia.genotype.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.genotype.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rsa_gia.genotype.genotype_name</code>.
     */
    public void setGenotypeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.genotype.genotype_name</code>.
     */
    public String getGenotypeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rsa_gia.genotype.organism_name</code>.
     */
    public void setOrganismName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rsa_gia.genotype.organism_name</code>.
     */
    public String getOrganismName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Genotype.GENOTYPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Genotype.GENOTYPE.GENOTYPE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Genotype.GENOTYPE.ORGANISM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGenotypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrganismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGenotypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrganismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenotypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenotypeRecord value2(String value) {
        setGenotypeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenotypeRecord value3(String value) {
        setOrganismName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenotypeRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GenotypeRecord
     */
    public GenotypeRecord() {
        super(Genotype.GENOTYPE);
    }

    /**
     * Create a detached, initialised GenotypeRecord
     */
    public GenotypeRecord(Integer id, String genotypeName, String organismName) {
        super(Genotype.GENOTYPE);

        set(0, id);
        set(1, genotypeName);
        set(2, organismName);
    }
}
