/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.Organism;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganismRecord extends UpdatableRecordImpl<OrganismRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = -1769017366;

    /**
     * Setter for <code>rsa_gia.organism.organism_name</code>.
     */
    public void setOrganismName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.organism.organism_name</code>.
     */
    public String getOrganismName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>rsa_gia.organism.species</code>.
     */
    public void setSpecies(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.organism.species</code>.
     */
    public String getSpecies() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rsa_gia.organism.subspecies</code>.
     */
    public void setSubspecies(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rsa_gia.organism.subspecies</code>.
     */
    public String getSubspecies() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rsa_gia.organism.variety</code>.
     */
    public void setVariety(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rsa_gia.organism.variety</code>.
     */
    public String getVariety() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Organism.ORGANISM.ORGANISM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Organism.ORGANISM.SPECIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Organism.ORGANISM.SUBSPECIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Organism.ORGANISM.VARIETY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getOrganismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSpecies();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSubspecies();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getVariety();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getOrganismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSpecies();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSubspecies();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getVariety();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganismRecord value1(String value) {
        setOrganismName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganismRecord value2(String value) {
        setSpecies(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganismRecord value3(String value) {
        setSubspecies(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganismRecord value4(String value) {
        setVariety(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganismRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganismRecord
     */
    public OrganismRecord() {
        super(Organism.ORGANISM);
    }

    /**
     * Create a detached, initialised OrganismRecord
     */
    public OrganismRecord(String organismName, String species, String subspecies, String variety) {
        super(Organism.ORGANISM);

        set(0, organismName);
        set(1, species);
        set(2, subspecies);
        set(3, variety);
    }
}
