/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.ProgramDependency;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramDependencyRecord extends UpdatableRecordImpl<ProgramDependencyRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1374972004;

    /**
     * Setter for <code>rsa_gia.program_dependency.program_id</code>.
     */
    public void setProgramId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.program_dependency.program_id</code>.
     */
    public Integer getProgramId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rsa_gia.program_dependency.program_dependency_id</code>.
     */
    public void setProgramDependencyId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.program_dependency.program_dependency_id</code>.
     */
    public Integer getProgramDependencyId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProgramDependency.PROGRAM_DEPENDENCY.PROGRAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProgramDependency.PROGRAM_DEPENDENCY.PROGRAM_DEPENDENCY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getProgramDependencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getProgramDependencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramDependencyRecord value1(Integer value) {
        setProgramId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramDependencyRecord value2(Integer value) {
        setProgramDependencyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramDependencyRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProgramDependencyRecord
     */
    public ProgramDependencyRecord() {
        super(ProgramDependency.PROGRAM_DEPENDENCY);
    }

    /**
     * Create a detached, initialised ProgramDependencyRecord
     */
    public ProgramDependencyRecord(Integer programId, Integer programDependencyId) {
        super(ProgramDependency.PROGRAM_DEPENDENCY);

        set(0, programId);
        set(1, programDependencyId);
    }
}
