/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.ProgramRun;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramRunRecord extends UpdatableRecordImpl<ProgramRunRecord> implements Record12<Integer, Integer, Integer, Integer, Byte, Byte, Timestamp, String, Integer, String, String, String> {

    private static final long serialVersionUID = -1023657620;

    /**
     * Setter for <code>rsa_gia.program_run.run_id</code>.
     */
    public void setRunId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.run_id</code>.
     */
    public Integer getRunId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rsa_gia.program_run.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rsa_gia.program_run.program_id</code>.
     */
    public void setProgramId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.program_id</code>.
     */
    public Integer getProgramId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rsa_gia.program_run.dataset_id</code>.
     */
    public void setDatasetId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.dataset_id</code>.
     */
    public Integer getDatasetId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>rsa_gia.program_run.saved</code>.
     */
    public void setSaved(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.saved</code>.
     */
    public Byte getSaved() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>rsa_gia.program_run.red_flag</code>.
     */
    public void setRedFlag(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.red_flag</code>.
     */
    public Byte getRedFlag() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>rsa_gia.program_run.run_date</code>.
     */
    public void setRunDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.run_date</code>.
     */
    public Timestamp getRunDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>rsa_gia.program_run.input_runs</code>.
     */
    public void setInputRuns(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.input_runs</code>.
     */
    public String getInputRuns() {
        return (String) get(7);
    }

    /**
     * Setter for <code>rsa_gia.program_run.saved_config_id</code>.
     */
    public void setSavedConfigId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.saved_config_id</code>.
     */
    public Integer getSavedConfigId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>rsa_gia.program_run.unsaved_config_contents</code>.
     */
    public void setUnsavedConfigContents(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.unsaved_config_contents</code>.
     */
    public String getUnsavedConfigContents() {
        return (String) get(9);
    }

    /**
     * Setter for <code>rsa_gia.program_run.descriptors</code>.
     */
    public void setDescriptors(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.descriptors</code>.
     */
    public String getDescriptors() {
        return (String) get(10);
    }

    /**
     * Setter for <code>rsa_gia.program_run.results</code>.
     */
    public void setResults(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.results</code>.
     */
    public String getResults() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Byte, Byte, Timestamp, String, Integer, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Byte, Byte, Timestamp, String, Integer, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProgramRun.PROGRAM_RUN.RUN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProgramRun.PROGRAM_RUN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ProgramRun.PROGRAM_RUN.PROGRAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ProgramRun.PROGRAM_RUN.DATASET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return ProgramRun.PROGRAM_RUN.SAVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return ProgramRun.PROGRAM_RUN.RED_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ProgramRun.PROGRAM_RUN.RUN_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ProgramRun.PROGRAM_RUN.INPUT_RUNS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return ProgramRun.PROGRAM_RUN.SAVED_CONFIG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return ProgramRun.PROGRAM_RUN.UNSAVED_CONFIG_CONTENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return ProgramRun.PROGRAM_RUN.DESCRIPTORS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ProgramRun.PROGRAM_RUN.RESULTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRunId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getSaved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getRedFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getRunDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getInputRuns();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getSavedConfigId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUnsavedConfigContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDescriptors();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getResults();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRunId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getSaved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getRedFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getRunDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getInputRuns();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getSavedConfigId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUnsavedConfigContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDescriptors();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getResults();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value1(Integer value) {
        setRunId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value3(Integer value) {
        setProgramId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value4(Integer value) {
        setDatasetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value5(Byte value) {
        setSaved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value6(Byte value) {
        setRedFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value7(Timestamp value) {
        setRunDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value8(String value) {
        setInputRuns(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value9(Integer value) {
        setSavedConfigId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value10(String value) {
        setUnsavedConfigContents(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value11(String value) {
        setDescriptors(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value12(String value) {
        setResults(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Byte value5, Byte value6, Timestamp value7, String value8, Integer value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProgramRunRecord
     */
    public ProgramRunRecord() {
        super(ProgramRun.PROGRAM_RUN);
    }

    /**
     * Create a detached, initialised ProgramRunRecord
     */
    public ProgramRunRecord(Integer runId, Integer userId, Integer programId, Integer datasetId, Byte saved, Byte redFlag, Timestamp runDate, String inputRuns, Integer savedConfigId, String unsavedConfigContents, String descriptors, String results) {
        super(ProgramRun.PROGRAM_RUN);

        set(0, runId);
        set(1, userId);
        set(2, programId);
        set(3, datasetId);
        set(4, saved);
        set(5, redFlag);
        set(6, runDate);
        set(7, inputRuns);
        set(8, savedConfigId);
        set(9, unsavedConfigContents);
        set(10, descriptors);
        set(11, results);
    }
}
