/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.ProgramRun;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramRunRecord extends UpdatableRecordImpl<ProgramRunRecord> implements Record12<Integer, Integer, Integer, Timestamp, Integer, String, Integer, String, String, Byte, Byte, String> {

    private static final long serialVersionUID = -398860971;

    /**
     * Setter for <code>rsa_gia.program_run.run_id</code>.
     */
    public void setRunId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.run_id</code>.
     */
    public Integer getRunId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rsa_gia.program_run.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rsa_gia.program_run.program_id</code>.
     */
    public void setProgramId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.program_id</code>.
     */
    public Integer getProgramId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rsa_gia.program_run.run_date</code>.
     */
    public void setRunDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.run_date</code>.
     */
    public Timestamp getRunDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>rsa_gia.program_run.dataset_id</code>.
     */
    public void setDatasetId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.dataset_id</code>.
     */
    public Integer getDatasetId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>rsa_gia.program_run.processed_path</code>.
     */
    public void setProcessedPath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.processed_path</code>.
     */
    public String getProcessedPath() {
        return (String) get(5);
    }

    /**
     * Setter for <code>rsa_gia.program_run.config_id</code>.
     */
    public void setConfigId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.config_id</code>.
     */
    public Integer getConfigId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>rsa_gia.program_run.config_contents</code>.
     */
    public void setConfigContents(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.config_contents</code>.
     */
    public String getConfigContents() {
        return (String) get(7);
    }

    /**
     * Setter for <code>rsa_gia.program_run.other_contents</code>.
     */
    public void setOtherContents(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.other_contents</code>.
     */
    public String getOtherContents() {
        return (String) get(8);
    }

    /**
     * Setter for <code>rsa_gia.program_run.saved</code>.
     */
    public void setSaved(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.saved</code>.
     */
    public Byte getSaved() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>rsa_gia.program_run.red_flag</code>.
     */
    public void setRedFlag(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.red_flag</code>.
     */
    public Byte getRedFlag() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>rsa_gia.program_run.results</code>.
     */
    public void setResults(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>rsa_gia.program_run.results</code>.
     */
    public String getResults() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Timestamp, Integer, String, Integer, String, String, Byte, Byte, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Timestamp, Integer, String, Integer, String, String, Byte, Byte, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProgramRun.PROGRAM_RUN.RUN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProgramRun.PROGRAM_RUN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ProgramRun.PROGRAM_RUN.PROGRAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ProgramRun.PROGRAM_RUN.RUN_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ProgramRun.PROGRAM_RUN.DATASET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ProgramRun.PROGRAM_RUN.PROCESSED_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ProgramRun.PROGRAM_RUN.CONFIG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ProgramRun.PROGRAM_RUN.CONFIG_CONTENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ProgramRun.PROGRAM_RUN.OTHER_CONTENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return ProgramRun.PROGRAM_RUN.SAVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return ProgramRun.PROGRAM_RUN.RED_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ProgramRun.PROGRAM_RUN.RESULTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRunId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getRunDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getProcessedPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getConfigId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getConfigContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getOtherContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component10() {
        return getSaved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component11() {
        return getRedFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getResults();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRunId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getRunDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getProcessedPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getConfigId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getConfigContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOtherContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getSaved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getRedFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getResults();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value1(Integer value) {
        setRunId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value3(Integer value) {
        setProgramId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value4(Timestamp value) {
        setRunDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value5(Integer value) {
        setDatasetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value6(String value) {
        setProcessedPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value7(Integer value) {
        setConfigId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value8(String value) {
        setConfigContents(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value9(String value) {
        setOtherContents(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value10(Byte value) {
        setSaved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value11(Byte value) {
        setRedFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord value12(String value) {
        setResults(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramRunRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Integer value5, String value6, Integer value7, String value8, String value9, Byte value10, Byte value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProgramRunRecord
     */
    public ProgramRunRecord() {
        super(ProgramRun.PROGRAM_RUN);
    }

    /**
     * Create a detached, initialised ProgramRunRecord
     */
    public ProgramRunRecord(Integer runId, Integer userId, Integer programId, Timestamp runDate, Integer datasetId, String processedPath, Integer configId, String configContents, String otherContents, Byte saved, Byte redFlag, String results) {
        super(ProgramRun.PROGRAM_RUN);

        set(0, runId);
        set(1, userId);
        set(2, programId);
        set(3, runDate);
        set(4, datasetId);
        set(5, processedPath);
        set(6, configId);
        set(7, configContents);
        set(8, otherContents);
        set(9, saved);
        set(10, redFlag);
        set(11, results);
    }
}
