/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.SavedConfig;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SavedConfigRecord extends UpdatableRecordImpl<SavedConfigRecord> implements Record5<Integer, Integer, String, String, Integer> {

    private static final long serialVersionUID = 219343992;

    /**
     * Setter for <code>rsa_gia.saved_config.config_id</code>.
     */
    public void setConfigId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.saved_config.config_id</code>.
     */
    public Integer getConfigId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rsa_gia.saved_config.program_id</code>.
     */
    public void setProgramId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.saved_config.program_id</code>.
     */
    public Integer getProgramId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rsa_gia.saved_config.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rsa_gia.saved_config.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rsa_gia.saved_config.contents</code>.
     */
    public void setContents(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rsa_gia.saved_config.contents</code>.
     */
    public String getContents() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rsa_gia.saved_config.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>rsa_gia.saved_config.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SavedConfig.SAVED_CONFIG.CONFIG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SavedConfig.SAVED_CONFIG.PROGRAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SavedConfig.SAVED_CONFIG.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SavedConfig.SAVED_CONFIG.CONTENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return SavedConfig.SAVED_CONFIG.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getConfigId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getConfigId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SavedConfigRecord value1(Integer value) {
        setConfigId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SavedConfigRecord value2(Integer value) {
        setProgramId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SavedConfigRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SavedConfigRecord value4(String value) {
        setContents(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SavedConfigRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SavedConfigRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SavedConfigRecord
     */
    public SavedConfigRecord() {
        super(SavedConfig.SAVED_CONFIG);
    }

    /**
     * Create a detached, initialised SavedConfigRecord
     */
    public SavedConfigRecord(Integer configId, Integer programId, String name, String contents, Integer userId) {
        super(SavedConfig.SAVED_CONFIG);

        set(0, configId);
        set(1, programId);
        set(2, name);
        set(3, contents);
        set(4, userId);
    }
}
