/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.enums.SeedExperimentTimepointValue;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.Seed;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeedRecord extends UpdatableRecordImpl<SeedRecord> implements Record13<Integer, String, String, String, String, Timestamp, SeedExperimentTimepointValue, String, Double, Double, Double, Double, Double> {

    private static final long serialVersionUID = 1672044713;

    /**
     * Setter for <code>rsa_gia.seed.seed_id</code>.
     */
    public void setSeedId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.seed_id</code>.
     */
    public Integer getSeedId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rsa_gia.seed.organism_name</code>.
     */
    public void setOrganismName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.organism_name</code>.
     */
    public String getOrganismName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rsa_gia.seed.experiment_code</code>.
     */
    public void setExperimentCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.experiment_code</code>.
     */
    public String getExperimentCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rsa_gia.seed.seed_name</code>.
     */
    public void setSeedName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.seed_name</code>.
     */
    public String getSeedName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rsa_gia.seed.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rsa_gia.seed.experiment_start_date</code>.
     */
    public void setExperimentStartDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.experiment_start_date</code>.
     */
    public Timestamp getExperimentStartDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>rsa_gia.seed.experiment_timepoint_value</code>.
     */
    public void setExperimentTimepointValue(SeedExperimentTimepointValue value) {
        set(6, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.experiment_timepoint_value</code>.
     */
    public SeedExperimentTimepointValue getExperimentTimepointValue() {
        return (SeedExperimentTimepointValue) get(6);
    }

    /**
     * Setter for <code>rsa_gia.seed.genotype</code>.
     */
    public void setGenotype(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.genotype</code>.
     */
    public String getGenotype() {
        return (String) get(7);
    }

    /**
     * Setter for <code>rsa_gia.seed.dry_shoot</code>.
     */
    public void setDryShoot(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.dry_shoot</code>.
     */
    public Double getDryShoot() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>rsa_gia.seed.dry_root</code>.
     */
    public void setDryRoot(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.dry_root</code>.
     */
    public Double getDryRoot() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>rsa_gia.seed.wet_shoot</code>.
     */
    public void setWetShoot(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.wet_shoot</code>.
     */
    public Double getWetShoot() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>rsa_gia.seed.wet_root</code>.
     */
    public void setWetRoot(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.wet_root</code>.
     */
    public Double getWetRoot() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>rsa_gia.seed.sterilization_chamber</code>.
     */
    public void setSterilizationChamber(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>rsa_gia.seed.sterilization_chamber</code>.
     */
    public Double getSterilizationChamber() {
        return (Double) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, Timestamp, SeedExperimentTimepointValue, String, Double, Double, Double, Double, Double> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, Timestamp, SeedExperimentTimepointValue, String, Double, Double, Double, Double, Double> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Seed.SEED.SEED_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Seed.SEED.ORGANISM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Seed.SEED.EXPERIMENT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Seed.SEED.SEED_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Seed.SEED.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Seed.SEED.EXPERIMENT_START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<SeedExperimentTimepointValue> field7() {
        return Seed.SEED.EXPERIMENT_TIMEPOINT_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Seed.SEED.GENOTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return Seed.SEED.DRY_SHOOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return Seed.SEED.DRY_ROOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field11() {
        return Seed.SEED.WET_SHOOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field12() {
        return Seed.SEED.WET_ROOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return Seed.SEED.STERILIZATION_CHAMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSeedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOrganismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getExperimentCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSeedName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getExperimentStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedExperimentTimepointValue component7() {
        return getExperimentTimepointValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getGenotype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component9() {
        return getDryShoot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component10() {
        return getDryRoot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component11() {
        return getWetShoot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component12() {
        return getWetRoot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component13() {
        return getSterilizationChamber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSeedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrganismName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getExperimentCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSeedName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getExperimentStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedExperimentTimepointValue value7() {
        return getExperimentTimepointValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getGenotype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getDryShoot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getDryRoot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value11() {
        return getWetShoot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value12() {
        return getWetRoot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getSterilizationChamber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value1(Integer value) {
        setSeedId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value2(String value) {
        setOrganismName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value3(String value) {
        setExperimentCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value4(String value) {
        setSeedName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value6(Timestamp value) {
        setExperimentStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value7(SeedExperimentTimepointValue value) {
        setExperimentTimepointValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value8(String value) {
        setGenotype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value9(Double value) {
        setDryShoot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value10(Double value) {
        setDryRoot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value11(Double value) {
        setWetShoot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value12(Double value) {
        setWetRoot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord value13(Double value) {
        setSterilizationChamber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeedRecord values(Integer value1, String value2, String value3, String value4, String value5, Timestamp value6, SeedExperimentTimepointValue value7, String value8, Double value9, Double value10, Double value11, Double value12, Double value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeedRecord
     */
    public SeedRecord() {
        super(Seed.SEED);
    }

    /**
     * Create a detached, initialised SeedRecord
     */
    public SeedRecord(Integer seedId, String organismName, String experimentCode, String seedName, String description, Timestamp experimentStartDate, SeedExperimentTimepointValue experimentTimepointValue, String genotype, Double dryShoot, Double dryRoot, Double wetShoot, Double wetRoot, Double sterilizationChamber) {
        super(Seed.SEED);

        set(0, seedId);
        set(1, organismName);
        set(2, experimentCode);
        set(3, seedName);
        set(4, description);
        set(5, experimentStartDate);
        set(6, experimentTimepointValue);
        set(7, genotype);
        set(8, dryShoot);
        set(9, dryRoot);
        set(10, wetShoot);
        set(11, wetRoot);
        set(12, sterilizationChamber);
    }
}
