#!/bin/sh
##############################################################################
##
## Start running the current version of the Rootwork (3D Reconstruction) program per image set without cropping 
##
## Fri May 31 2013 Vladimir Popov <vladimir.popov@duke.edu> 
##
################################################################################


reconDir="/usr/local/bin/matlab-programs/Reconstruction3D"

MATLABPATH="$MATLABPATH:${reconDir}"
export MATLABPATH
echo MATLABPATH=$MATLABPATH

matlab -nosplash -nodesktop -nodisplay -r "rootwork('$1','$2','');exit"
