#!/bin/sh
################################################################################\
##
## Copy templates from the /usr/tmp/rsa-gia-templates to the /data/rsa/rsa-gia-templates 
## and sets default permissions in the /data/rsa/rsa-gia-templates folder
## 
## NOTE: Before using this script,make sure that:
##
##       -- you already ran rsa-create-orig script
##       -- you already ran the rsapipeline RPM (so, the templates are in the /usr/tmp folder)
##  
##
## Fri May 31 2013 Vladimir Popov <vladimir.popov@duke.edu>   
##    
################################################################################

echo
echo "=== Starting the $0 script =="
echo

if [ $USER != "root" ]; then
    echo "ERROR: this script must be executed under 'root' account."
    echo
    exit 1
fi

src_tmplt='/usr/local/bin/rsa-gia-templates/*'
dest_tmplt='/data/rsa/rsa-gia-templates'

echo
echo "=== Setting default permissions for directory /data/rsa/rsa-gia-templates ==="
echo
chown rsa-data:rootarch $dest_tmplt
chmod 2750 $dest_tmplt 

echo
echo "=== Copy templates from the $src_tmplt to the /data/rsa/rsa-gia-templates ==="
echo
cp -r $src_tmplt $dest_tmplt

echo
echo "=== Setting access rights for $dest_tmplt ==="
echo

echo "1) Owner for all files and subdirectories will be set to 'rsa-data'."
echo "2) Group for all files and subdirectories will be set to 'rootarch'."
echo "3) Permissions for all subdirectories will be set to 2750."
echo "4) Permissions for all files will be set to 640."
echo

# directories
find $dest_tmplt -mindepth 1 -type d -exec chown rsa-data:rootarch '{}' \;
find $dest_tmplt -mindepth 1 -type d -exec chmod 2750 '{}' \;
# files
find $dest_tmplt -mindepth 1 -type f -exec chown rsa-data:rootarch '{}' \;
find $dest_tmplt -mindepth 1 -type f -exec chmod 640 '{}' \;

echo
echo "=== Clean up: removing the $src_tmplt folder ==="
echo
rm -r /usr/local/bin/rsa-gia-templates

echo
echo "=== Done ==="
echo
