/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.Indexes;
import org.danforthcenter.genome.rootarch.rsagia.db.Keys;
import org.danforthcenter.genome.rootarch.rsagia.db.RsaGia;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.records.DatasetImagePathsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetImagePaths extends TableImpl<DatasetImagePathsRecord> {

    private static final long serialVersionUID = -372928558;

    /**
     * The reference instance of <code>rsa_gia.dataset_image_paths</code>
     */
    public static final DatasetImagePaths DATASET_IMAGE_PATHS = new DatasetImagePaths();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatasetImagePathsRecord> getRecordType() {
        return DatasetImagePathsRecord.class;
    }

    /**
     * The column <code>rsa_gia.dataset_image_paths.dataset_id</code>.
     */
    public final TableField<DatasetImagePathsRecord, Integer> DATASET_ID = createField("dataset_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rsa_gia.dataset_image_paths.image_type</code>.
     */
    public final TableField<DatasetImagePathsRecord, String> IMAGE_TYPE = createField("image_type", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>rsa_gia.dataset_image_paths.image_path</code>.
     */
    public final TableField<DatasetImagePathsRecord, String> IMAGE_PATH = createField("image_path", org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>rsa_gia.dataset_image_paths</code> table reference
     */
    public DatasetImagePaths() {
        this(DSL.name("dataset_image_paths"), null);
    }

    /**
     * Create an aliased <code>rsa_gia.dataset_image_paths</code> table reference
     */
    public DatasetImagePaths(String alias) {
        this(DSL.name(alias), DATASET_IMAGE_PATHS);
    }

    /**
     * Create an aliased <code>rsa_gia.dataset_image_paths</code> table reference
     */
    public DatasetImagePaths(Name alias) {
        this(alias, DATASET_IMAGE_PATHS);
    }

    private DatasetImagePaths(Name alias, Table<DatasetImagePathsRecord> aliased) {
        this(alias, aliased, null);
    }

    private DatasetImagePaths(Name alias, Table<DatasetImagePathsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return RsaGia.RSA_GIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DATASET_IMAGE_PATHS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DatasetImagePathsRecord> getPrimaryKey() {
        return Keys.KEY_DATASET_IMAGE_PATHS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DatasetImagePathsRecord>> getKeys() {
        return Arrays.<UniqueKey<DatasetImagePathsRecord>>asList(Keys.KEY_DATASET_IMAGE_PATHS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DatasetImagePathsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DatasetImagePathsRecord, ?>>asList(Keys.DATASET_IMAGE_PATHS_DATASET_DATASET_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DatasetImagePaths as(String alias) {
        return new DatasetImagePaths(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DatasetImagePaths as(Name alias) {
        return new DatasetImagePaths(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetImagePaths rename(String name) {
        return new DatasetImagePaths(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetImagePaths rename(Name name) {
        return new DatasetImagePaths(name, null);
    }
}
