/*
 * This file is generated by jOOQ.
*/
package org.danforthcenter.genome.rootarch.rsagia.db;


import javax.annotation.Generated;

import org.danforthcenter.genome.rootarch.rsagia.db.tables.Dataset;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.DatasetImageType;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.Experiment;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.Genotype;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.Organism;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.Program;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.ProgramDependency;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.ProgramRun;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.SavedConfig;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.Seed;
import org.danforthcenter.genome.rootarch.rsagia.db.tables.User;


/**
 * Convenience access to all tables in rsa_gia
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rsa_gia.dataset</code>.
     */
    public static final Dataset DATASET = org.danforthcenter.genome.rootarch.rsagia.db.tables.Dataset.DATASET;

    /**
     * The table <code>rsa_gia.dataset_image_type</code>.
     */
    public static final DatasetImageType DATASET_IMAGE_TYPE = org.danforthcenter.genome.rootarch.rsagia.db.tables.DatasetImageType.DATASET_IMAGE_TYPE;

    /**
     * The table <code>rsa_gia.experiment</code>.
     */
    public static final Experiment EXPERIMENT = org.danforthcenter.genome.rootarch.rsagia.db.tables.Experiment.EXPERIMENT;

    /**
     * The table <code>rsa_gia.genotype</code>.
     */
    public static final Genotype GENOTYPE = org.danforthcenter.genome.rootarch.rsagia.db.tables.Genotype.GENOTYPE;

    /**
     * The table <code>rsa_gia.organism</code>.
     */
    public static final Organism ORGANISM = org.danforthcenter.genome.rootarch.rsagia.db.tables.Organism.ORGANISM;

    /**
     * The table <code>rsa_gia.program</code>.
     */
    public static final Program PROGRAM = org.danforthcenter.genome.rootarch.rsagia.db.tables.Program.PROGRAM;

    /**
     * The table <code>rsa_gia.program_dependency</code>.
     */
    public static final ProgramDependency PROGRAM_DEPENDENCY = org.danforthcenter.genome.rootarch.rsagia.db.tables.ProgramDependency.PROGRAM_DEPENDENCY;

    /**
     * The table <code>rsa_gia.program_run</code>.
     */
    public static final ProgramRun PROGRAM_RUN = org.danforthcenter.genome.rootarch.rsagia.db.tables.ProgramRun.PROGRAM_RUN;

    /**
     * The table <code>rsa_gia.saved_config</code>.
     */
    public static final SavedConfig SAVED_CONFIG = org.danforthcenter.genome.rootarch.rsagia.db.tables.SavedConfig.SAVED_CONFIG;

    /**
     * The table <code>rsa_gia.seed</code>.
     */
    public static final Seed SEED = org.danforthcenter.genome.rootarch.rsagia.db.tables.Seed.SEED;

    /**
     * The table <code>rsa_gia.user</code>.
     */
    public static final User USER = org.danforthcenter.genome.rootarch.rsagia.db.tables.User.USER;
}
